Implement support for PrintPage command
Vrtgs/thirtyfour pull request #4
Opened 2024-08-22 07:14 UTC by alexandru0-dev

As title says, this PR is for supporting and exposing the PrintPage command.
The only thing that could be improved is not relying on the webdriver crate for PrintParameters (Tho is a pretty long/complex struct so idk)

Already tested myself and works as expected

2024-08-23 12:27 UTC, Vrtgs requested changes
looks great! but the webdriver dependency is big and we don't use it for now, and so I would like it if you add a

`src/common/print.rs`
```rs
use std::sync::Arc;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrintPageRange {
    Integer(u64),
    Range(Arc<str>),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct PrintParameters {
    pub orientation: PrintOrientation,
    pub scale: f64,
    pub background: bool,
    pub page: PrintPage,
    pub margin: PrintMargins,
    pub page_ranges: Arc<[PrintPageRange]>,
    pub shrink_to_fit: bool,
}

impl Default for PrintParameters {
    fn default() -> Self {
        PrintParameters {
            orientation: PrintOrientation::default(),
            scale: 1.0,
            background: false,
            page: PrintPage::default(),
            margin: PrintMargins::default(),
            page_ranges: Arc::new([]),
            shrink_to_fit: true,
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PrintOrientation {
    Landscape,
    #[default]
    Portrait,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PrintPage {
    pub width: f64,
    pub height: f64,
}

impl Default for PrintPage {
    fn default() -> Self {
        PrintPage {
            width: 21.59,
            height: 27.94,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PrintMargins {
    pub top: f64,
    pub bottom: f64,
    pub left: f64,
    pub right: f64,
}

impl Default for PrintMargins {
    fn default() -> Self {
        PrintMargins {
            top: 1.0,
            bottom: 1.0,
            left: 1.0,
            right: 1.0,
        }
    }
}
```

2024-08-23 16:12 UTC, alexandru0-dev commented
As I assumed, I'm also adding a test for printing in the meantime.
One "issue: that I found is clippy complaining about missing docs, and I'm adding them.
The default page size shouldn't something like A4?

2024-08-23 17:02 UTC, alexandru0-dev reviewed
Webdriver dependency remove and included inside the crate, also included docs and a test

2024-08-23 17:06 UTC, alexandru0-dev reviewed
Webdriver dependency remove and included inside the crate, also included docs and a test

2024-08-24 09:08 UTC, Vrtgs commented on thirtyfour/src/common/command.rs
> +                    .add_body(serde_json::to_value(params).expect("DioCane"))
why is this `.expect("DioCane")`? I mean I just want to know the madness behind it

2024-08-24 09:10 UTC, Vrtgs commented
looks gread and I'd be happy to merge this if you resolve my concerns with this

2024-08-24 09:51 UTC, alexandru0-dev commented on thirtyfour/src/common/command.rs
> +                    .add_body(serde_json::to_value(params).expect("DioCane"))
AHAHHAHHAJHAH
That's a genuine mistake that I've forgotten to remove while testing 
I'm going to fix it immediately

2024-08-24 10:20 UTC, Vrtgs commented on thirtyfour/src/common/command.rs
> +                    .add_body(serde_json::to_value(params).expect("DioCane"))
Nah it's fineeee I do plenty if things like that, but I'd just not want them to sneak to a public repo everyone is going to use

2024-08-24 10:23 UTC, alexandru0-dev commented on thirtyfour/src/common/command.rs
> +                    .add_body(serde_json::to_value(params).expect("DioCane"))
You're completely right, I completely forgot about it as I was still messing around at the time
Fixed and rebased

2024-08-24 10:24 UTC, alexandru0-dev commented on thirtyfour/src/common/command.rs
> +                    .add_body(serde_json::to_value(params).expect("DioCane"))
It's a profanity btw, so i think deleting any references to it if possible would be ideal

2024-08-24 10:26 UTC, Vrtgs approved these changes
Looks good

2024-08-24 10:32 UTC, alexandru0-dev commented
It's linting, i can fix that immediately
btw could you take a look at the last comment on the last review request?

2024-08-24 10:34 UTC, Vrtgs commented
fix the lint ci, the rest of the tests are wonky for now

2024-08-24 10:45 UTC, merged